### ISSUE TITLE
DataStream: consider iterator instead of lists or support both

### ISSUE THREAD

**Issue by shubhamchandak94** [kedartatwawadi/stanford_compression_library#3]
We can consider using iterators instead of lists as the DataStream type. I can think of pros and cons of each strategy - lists are better for working in blocks and supporting things like counts and empirical distribution. Iterators are more suitable for streaming compressors like arithmetic coding. Perhaps we can support both "DataStream" and "DataBlock" with conversions between them when appropriate.

**Comment by tpulkit** [comment]
I like the idea of supporting both. I am assuming both "DataStream" and "DataBlock" be independent of the actual compression method?

**Comment by kedartatwawadi** [comment]
Some template to start with
```
diff --git a/core/data_stream.py b/core/data_stream.py
index 48a75fd..ad50dd4 100644
--- a/core/data_stream.py
+++ b/core/data_stream.py
@@ -1,16 +1,33 @@
+import abc
 from typing import List, Set
 from dataclasses import dataclass
 from core.util import compute_alphabet, compute_counts_dict
 from core.prob_dist import ProbabilityDist
 
 
-class DataStream:
+
+class DataStreamBase(abc.ABC):
+
+    @abc.abstractmethod
+    def next(self):
+        pass
+
+    @abc.abstractmethod
+    def reset(self):
+        pass
+
+    @abc.abstractmethod
+    def size(self):
+        pass
+    
+
+class DataStream(DataStreamBase):
     """
     FIXME: for now data is only presented as a list of symbols
     """
 
     def __init__(self, data_list: List):
-        self.data_list = data_list
+        self._data_list = data_list
```

**Comment by kedartatwawadi** [comment]
@shubhamchandak94: Is this resolved now? Considering we fully changed the structure?

**Comment by shubhamchandak94** [comment]
Yes
