### ISSUE TITLE
Add more test framework for compressors

### ISSUE THREAD

**Issue by kedartatwawadi** [kedartatwawadi/stanford_compression_library#32]
We have the following tests: 
- [x] Tests which check if a `data_block` can be encoded losslessly
- [x] Tests if a file can be encoded losslessly.

We however also need to check if the `num_bits_consumed` returned by the decoder is correct. This would likely involve appending the `encoded_bitarray` from encoder with some garbage and then checking if the decoder still works.

**Comment by tpulkit** [comment]
Add a test on just encoder: expected encoded codeword versus produced by the code
