### ISSUE TITLE
Clean-up Child Node being None in BinaryTree

### ISSUE THREAD

**Issue by tpulkit** [kedartatwawadi/stanford_compression_library#43]
https://github.com/kedartatwawadi/stanford_compression_library/blob/5809489d83f4e3d2ac07995aef8f7f99b48057e3/compressors/fano_coder.py#L74

**Comment by tpulkit** [comment]
https://stackoverflow.com/questions/55777748/updating-none-value-does-not-reflect-in-the-object

**Comment by kedartatwawadi** [comment]
closing this, as rewriting the Shannon coder code mitigated the issuer
